// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/dupreehkuda/TaskBingo/internal/usecases/user_stats/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
	isgomock struct{}
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// FetchFinishedGames mocks base method.
func (m *Mockstorage) FetchFinishedGames(ctx context.Context, userID string, from time.Time) ([]entity.GameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFinishedGames", ctx, userID, from)
	ret0, _ := ret[0].([]entity.GameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFinishedGames indicates an expected call of FetchFinishedGames.
func (mr *MockstorageMockRecorder) FetchFinishedGames(ctx, userID, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFinishedGames", reflect.TypeOf((*Mockstorage)(nil).FetchFinishedGames), ctx, userID, from)
}
