services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: taskbingo-nginx
    restart: always
    depends_on:
      - server
      - web
    ports:
      - '8080:80'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskbingo-server
    restart: always
    environment:
      - GAME_SERVICE_ADDRESS=:8082
      - DATABASE_DSN=${DATABASE_DSN}
      - secret=${SECRET}
      - CURRENT_DOMAIN=${CURRENT_DOMAIN}
      - ALLOWED_WS_ORIGINS=${ALLOWED_WS_ORIGINS}
      - MIGRATIONS_PATH=/app/migrations/postgresql
    expose:
      - '8082'

  web:
    build:
      context: ./bingo-app
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_WS_URL: ${VITE_WS_URL}
        VITE_WEB_URL: ${VITE_WEB_URL}
    container_name: taskbingo-web
    restart: always
    depends_on:
      - server
    expose:
      - '3000'
