version: '3.4'

services:
  server:
    build: .
    container_name: taskbingo-server
    environment:
      - GAME_SERVICE_ADDRESS=${GAME_SERVICE_ADDRESS}
      - DATABASE_DSN=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - secret=${SECRET}
      - CURRENT_DOMAIN=${CURRENT_DOMAIN}
      - ALLOWED_WS_ORIGINS=${ALLOWED_WS_ORIGINS}
      - MIGRATIONS_PATH=/app/migrations/postgresql
    env_file: .env
    ports:
      - '8082:8082'
    restart: always
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:latest
    container_name: taskbingo-postgres
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
