version: '3.9'

services:
#  bingo-app:
#    build:
#      dockerfile: ./bingo-app/Dockerfile
#    container_name: bingo-app
#    ports:
#      - '5173:5173'
#    restart: on-failure
#    volumes:
#      - .:/app
#    depends_on:
#      user-service:
#        condition: service_started
#      user-database:
#        condition: service_started

  user-service:
    build:
      dockerfile: ./user-data-service/Dockerfile
    container_name: user-service
    environment:
      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@user-db:${DB_PORT}/${DB_NAME}
      - RUN_ADDRESS=${ADDRESS}
    env_file: .env
    ports:
      - '8081:8081'
    restart: on-failure
    volumes:
      - .:/user_service
    depends_on:
      user-database:
        condition: service_started

  user-database:
    image: postgres:latest
    container_name: user-db
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'