// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/dupreehkuda/TaskBingo/internal/usecases/user_login/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockcredsFetcher is a mock of credsFetcher interface.
type MockcredsFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockcredsFetcherMockRecorder
	isgomock struct{}
}

// MockcredsFetcherMockRecorder is the mock recorder for MockcredsFetcher.
type MockcredsFetcherMockRecorder struct {
	mock *MockcredsFetcher
}

// NewMockcredsFetcher creates a new mock instance.
func NewMockcredsFetcher(ctrl *gomock.Controller) *MockcredsFetcher {
	mock := &MockcredsFetcher{ctrl: ctrl}
	mock.recorder = &MockcredsFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcredsFetcher) EXPECT() *MockcredsFetcherMockRecorder {
	return m.recorder
}

// FetchByUsername mocks base method.
func (m *MockcredsFetcher) FetchByUsername(ctx context.Context, username string) (storage.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUsername", ctx, username)
	ret0, _ := ret[0].(storage.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUsername indicates an expected call of FetchByUsername.
func (mr *MockcredsFetcherMockRecorder) FetchByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUsername", reflect.TypeOf((*MockcredsFetcher)(nil).FetchByUsername), ctx, username)
}

// Mockhasher is a mock of hasher interface.
type Mockhasher struct {
	ctrl     *gomock.Controller
	recorder *MockhasherMockRecorder
	isgomock struct{}
}

// MockhasherMockRecorder is the mock recorder for Mockhasher.
type MockhasherMockRecorder struct {
	mock *Mockhasher
}

// NewMockhasher creates a new mock instance.
func NewMockhasher(ctrl *gomock.Controller) *Mockhasher {
	mock := &Mockhasher{ctrl: ctrl}
	mock.recorder = &MockhasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhasher) EXPECT() *MockhasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *Mockhasher) Hash(password, salt string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password, salt)
	ret0, _ := ret[0].(string)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockhasherMockRecorder) Hash(password, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*Mockhasher)(nil).Hash), password, salt)
}

// MocktokenSigner is a mock of tokenSigner interface.
type MocktokenSigner struct {
	ctrl     *gomock.Controller
	recorder *MocktokenSignerMockRecorder
	isgomock struct{}
}

// MocktokenSignerMockRecorder is the mock recorder for MocktokenSigner.
type MocktokenSignerMockRecorder struct {
	mock *MocktokenSigner
}

// NewMocktokenSigner creates a new mock instance.
func NewMocktokenSigner(ctrl *gomock.Controller) *MocktokenSigner {
	mock := &MocktokenSigner{ctrl: ctrl}
	mock.recorder = &MocktokenSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenSigner) EXPECT() *MocktokenSignerMockRecorder {
	return m.recorder
}

// Sign mocks base method.
func (m *MocktokenSigner) Sign(userID, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", userID, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MocktokenSignerMockRecorder) Sign(userID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MocktokenSigner)(nil).Sign), userID, username)
}
