name: build & push web

on:
  push:
    branches:
      - release/**
      - stage/**
    paths:
      - bingo-app/**

jobs:
  build-and-push-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push web image
        uses: docker/build-push-action@v2
        with:
          context: ./bingo-app
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bingo-web-stage:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/bingo-web-stage:latest