name: deploy

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["build & push"]
    types:
      - completed

jobs:
  deploy-timeweb:
      runs-on: ubuntu-latest

      steps:
        - name: Deploy on timeweb
          uses: appleboy/ssh-action@master
          with:
            host: ${{ vars.TIMEWEB_IP }}
            username: ${{ vars.TIMEWEB_USERNAME }}
            password: ${{ secrets.TIMEWEB_PASSWORD }}
            script: |
              cd TaskBingo
              make deploy